import { iButton } from './iButton';
export const Buttons: iButton[] = [
  {
    btnID: 'Filename1',
    btnTitle: '1',
    fileName: 'Filename1',
    useTrackTitle: true,
    audioData: '',
    volume: 70,
    color: 'purple',
    inGroup: false,
    loop: false,
    trimStart: 200,
    trimEnd: 4,
    isActive: false,
  },
  {
    btnID: 'Filename2',
    btnTitle: '2',
    fileName: 'Filename2',
    useTrackTitle: false,
    audioData: '',
    volume: 46,
    color: 'purple',
    inGroup: true,
    loop: true,
    trimStart: 2,
    trimEnd: 10,
    isActive: false,
  },
  {
    btnID: 'Filename3',
    btnTitle: '3',
    fileName: 'Filename3',
    useTrackTitle: false,
    audioData: '',
    volume: 25,
    color: 'purple',
    inGroup: true,
    loop: true,
    trimStart: 2,
    trimEnd: 10,
    isActive: false,
  },
  {
    btnID: 'Filename4',
    btnTitle: '4',
    fileName: 'Filename4',
    useTrackTitle: true,
    audioData: '',
    volume: 88,
    color: 'poo',
    inGroup: false,
    loop: true,
    trimStart: 2,
    trimEnd: 10,
    isActive: false,
  },
  {
    btnID: 'Filename5',
    btnTitle: '5',
    fileName: 'Filename5',
    useTrackTitle: true,
    audioData: '',
    volume: 88,
    color: 'poo',
    inGroup: true,
    loop: true,
    trimStart: 2,
    trimEnd: 10,
    isActive: false,
  },
  {
    btnID: 'Filename6',
    btnTitle: '6',
    fileName: 'Filename6',
    useTrackTitle: true,
    audioData: '',
    volume: 88,
    color: 'poo',
    inGroup: true,
    loop: true,
    trimStart: 2,
    trimEnd: 10,
    isActive: false,
  },
];
