import { iButton } from './iButton';
export const Buttons: iButton[] = [
  {
    btnId: 1,
    btnTitle: 'Title1',
    fileName: 'Filename1',
    useTrackTitle: true,
    audioData: '',
    volume: 70,
    color: 'purple',
    inGroup: true,
    loop: false,
    trimStart: 200,
    trimEnd: 4,
    isActive: false,
  },
  {
    btnId: 2,
    btnTitle: 'Title2',
    fileName: 'Filename2',
    useTrackTitle: false,
    audioData: '',
    volume: 46,
    color: 'green',
    inGroup: false,
    loop: true,
    trimStart: 2,
    trimEnd: 10,
    isActive: false,
  },
  {
    btnId: 3,
    btnTitle: 'Title3',
    fileName: 'Filename3',
    useTrackTitle: false,
    audioData: '',
    volume: 25,
    color: 'purple',
    inGroup: false,
    loop: true,
    trimStart: 2,
    trimEnd: 10,
    isActive: false,
  },
  {
    btnId: 4,
    btnTitle: 'Title4',
    fileName: 'Filename4',
    useTrackTitle: true,
    audioData: '',
    volume: 88,
    color: 'purple',
    inGroup: true,
    loop: true,
    trimStart: 2,
    trimEnd: 10,
    isActive: false,
  },
];
