import { iButton } from './iButton';
export const Buttons: iButton[] = [];

// ===============EXAMPLE_DATA==============
// {
//   btnID: '78658764187',
//   btnTitle: '1',
//   fileName: 'Filename1',
//   useTrackTitle: true,
//   audioData: 'fhasdlofiuawo4;8fyuawp;9o8fyua;oweifgha;oes98fy',
//   volume: 70,
//   color: 'green',
//   inGroup: false,
//   loop: false,
//   trimStart: 200,
//   trimEnd: 4,
//   isActive: false,
//   btnDisabled: false,
// },
// {
//   btnID: '6546432328756',
//   btnTitle: '2231',
//   fileName: 'Filename212312',
//   useTrackTitle: false,
//   audioData: '',
//   volume: 20,
//   color: 'yellow',
//   inGroup: true,
//   loop: true,
//   trimStart: 2,
//   trimEnd: 10,
//   isActive: false,
//   btnDisabled: false,
// },
// {
//   btnID: '654632523328756',
//   btnTitle: '28458',
//   fileName: 'Filename223523',
//   useTrackTitle: false,
//   audioData: '',
//   volume: 20,
//   color: 'teal',
//   inGroup: true,
//   loop: true,
//   trimStart: 2,
//   trimEnd: 10,
//   isActive: false,
//   btnDisabled: false,
// },
// {
//   btnID: '654632623628756',
//   btnTitle: '26236',
//   fileName: 'Filename27547',
//   useTrackTitle: false,
//   audioData: '',
//   volume: 20,
//   color: 'blue',
//   inGroup: true,
//   loop: true,
//   trimStart: 2,
//   trimEnd: 10,
//   isActive: false,
//   btnDisabled: false,
// },
// {
//   btnID: '6546328764756',
//   btnTitle: '27247',
//   fileName: 'Filename284584',
//   useTrackTitle: false,
//   audioData: '',
//   volume: 20,
//   color: 'orange',
//   inGroup: true,
//   loop: true,
//   trimStart: 2,
//   trimEnd: 10,
//   isActive: false,
//   btnDisabled: false,
// },
// {
//   btnID: '6546324328756',
//   btnTitle: '27538',
//   fileName: 'Filename2236274',
//   useTrackTitle: false,
//   audioData: '',
//   volume: 20,
//   color: 'orange',
//   inGroup: true,
//   loop: true,
//   trimStart: 2,
//   trimEnd: 10,
//   isActive: false,
//   btnDisabled: false,
// },
// {
//   btnID: '65463864848628756',
//   btnTitle: '22362538',
//   fileName: 'Filename0780782',
//   useTrackTitle: false,
//   audioData: '',
//   volume: 20,
//   color: 'poo',
//   inGroup: true,
//   loop: true,
//   trimStart: 2,
//   trimEnd: 10,
//   isActive: false,
//   btnDisabled: false,
// },
// {
//   btnID: '3696375746',
//   btnTitle: '3',
//   fileName: 'Filename3',
//   useTrackTitle: false,
//   audioData: '',
//   volume: 10,
//   color: 'purple',
//   inGroup: true,
//   loop: true,
//   trimStart: 2,
//   trimEnd: 10,
//   isActive: false,
//   btnDisabled: false,
// },
